### ISSUE TITLE
Incompatibility with Custom Updater

### ISSUE THREAD

**Issue by emouawad** [briis/ha-weather-card-extended#3]
The old custom_updater will be deprecated and will stop eventually from working - The functionality has been migrated  to Home Assistant Community Store (https://hacs.netlify.com/ is han)

This beautifully designed card is incompatible with it.
Please let me know if i can help testing - I have a working setup

**Comment by emouawad** [comment]
@briis - Any Chance you could add support for HACS?
I would if i knew how? :(

That'd be super helpful to everyone - thanks

**Comment by briis** [comment]
I have not looked at this card for close to a year, and was not planning on supporting it any more, as many other people with better Frontend skills than me, since then have made better cards. (I am more in to the backend stuff).
I suggest that you go to HACS and then in Frontend search for Weather, I think you will some great cards that are better than this.
